# https://scrutinizer-ci.com/docs/configuration/build_reference
build:
  image: default-bionic
  environment:
    timezone: UTC
    php:
      version: "8.1"
      ini:
        memory_limit: "-1"
  tests:
    override:
      - echo "Skipping tests"

# https://scrutinizer-ci.com/docs/reviews/excluding_files_from_analysis
filter:
  paths:
    - 'public/'
    - 'Core/'
    - 'Modules/'
    - 'Dolibarr/'
  excluded_paths:
    - 'test/'
    - 'vendor/'
    - 'public/htdocs/includes/'
  dependency_paths:
    - 'vendor/'
    - 'public/htdocs/includes/'
