# https://scrutinizer-ci.com/docs/configuration/build_reference
build:
  image: default-bionic
  environment:
    timezone: UTC
    php:
      version: "8.1"
      ini:
        memory_limit: "-1"
    mysql: 5.7
#  services:
#    mysql:
#      image: "mysql:8.0"
#      env:
#        MYSQL_ROOT_PASSWORD: "root"
#        MYSQL_DATABASE: "alixar_test"
  dependencies:
    before:
      - composer install --prefer-dist --no-interaction
  tests:
    before:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS alixar_test;'
    override:
      - php ./vendor/bin/phpunit --configuration phpunit.xml

# https://scrutinizer-ci.com/docs/reviews/excluding_files_from_analysis
filter:
  paths:
    - 'public/'
    - 'Core/'
    - 'Modules/'
    - 'Dolibarr/'
  excluded_paths:
    - 'test/'
    - 'vendor/'
    - 'public/htdocs/includes/'
  dependency_paths:
    - 'vendor/'
    - 'public/htdocs/includes/'
