# https://scrutinizer-ci.com/docs/configuration/build_reference
build:
  image: default-bionic
  environment:
    timezone: UTC
    php:
      version: "8.1"
      ini:
        memory_limit: "-1"
  nodes:
    my-node:
      services:
        mysql: 5.7
        MYSQL_ALLOW_EMPTY_PASSWORD:
          'yes'
        MYSQL_DATABASE: alixar_tests
  dependencies:
    before:
      - composer install --prefer-dist --no-interaction
      - mysql -u root -h 127.0.0.1 -P 3306 'DROP DATABASE IF EXISTS alixar_tests;'
      - mysql -u root -h 127.0.0.1 -P 3306 'CREATE DATABASE IF NOT EXISTS alixar_tests;'
  tests:
    override:
      - php ./vendor/bin/phpunit --configuration phpunit.xml

# https://scrutinizer-ci.com/docs/reviews/excluding_files_from_analysis
filter:
  paths:
    - 'public/'
    - 'Core/'
    - 'Modules/'
    - 'Dolibarr/'
  excluded_paths:
    - 'test/'
    - 'vendor/'
    - 'public/htdocs/includes/'
  dependency_paths:
    - 'vendor/'
    - 'public/htdocs/includes/'
