# https://scrutinizer-ci.com/docs/configuration/build_reference
build:
  image: default-bionic
  environment:
    timezone: UTC
    php:
      version: "8.1"
      ini:
        memory_limit: "-1"
  nodes:
    my-node:
      services:
        mysql:
          image: "mysql:5.7"
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: alixar_tests
  dependencies:
    before:
      - composer install --prefer-dist --no-interaction
  tests:
    override:
      - php ./vendor/bin/phpunit --configuration phpunit.xml

# https://scrutinizer-ci.com/docs/reviews/excluding_files_from_analysis
filter:
  paths:
    - 'public/'
    - 'Core/'
    - 'Modules/'
    - 'Dolibarr/'
  excluded_paths:
    - 'test/'
    - 'vendor/'
    - 'public/htdocs/includes/'
  dependency_paths:
    - 'vendor/'
    - 'public/htdocs/includes/'
