services:
  web:
    image: nginx:alpine
    container_name: alixar_httpd
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: alixar_php
    volumes:
      - ../:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: alixar_db
      MYSQL_USER: alixar_user
      MYSQL_PASSWORD: alixar_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: