<?php

namespace Modules\Alixar\Model;

use Alxarafe\Base\Model\Model;

/**
 * Class Product
 * Represents table product
 */
class Product extends Model
{
    protected $table = 'product';
    protected $primaryKey = 'rowid';
    public $timestamps = false;

    protected $fillable = [
        'ref',
        'entity',
        'ref_ext',
        'datec',
        'fk_parent',
        'label',
        'description',
        'note_public',
        'note',
        'customcode',
        'fk_country',
        'fk_state',
        'price',
        'price_ttc',
        'price_min',
        'price_min_ttc',
        'price_base_type',
        'price_label',
        'cost_price',
        'default_vat_code',
        'tva_tx',
        'recuperableonly',
        'localtax1_tx',
        'localtax1_type',
        'localtax2_tx',
        'localtax2_type',
        'fk_user_author',
        'fk_user_modif',
        'tosell',
        'tobuy',
        'tobatch',
        'sell_or_eat_by_mandatory',
        'batch_mask',
        'fk_product_type',
        'duration',
        'seuil_stock_alerte',
        'url',
        'barcode',
        'fk_barcode_type',
        'accountancy_code_sell',
        'accountancy_code_sell_intra',
        'accountancy_code_sell_export',
        'accountancy_code_buy',
        'accountancy_code_buy_intra',
        'accountancy_code_buy_export',
        'partnumber',
        'net_measure',
        'net_measure_units',
        'weight',
        'weight_units',
        'length',
        'length_units',
        'width',
        'width_units',
        'height',
        'height_units',
        'surface',
        'surface_units',
        'volume',
        'volume_units',
        'stockable_product',
        'stock',
        'pmp',
        'fifo',
        'lifo',
        'fk_default_warehouse',
        'fk_default_bom',
        'fk_default_workstation',
        'canvas',
        'finished',
        'lifetime',
        'qc_frequency',
        'hidden',
        'import_key',
        'model_pdf',
        'fk_price_expression',
        'desiredstock',
        'fk_unit',
        'price_autogen',
        'fk_project',
        'mandatory_period',
        'last_main_doc',
    ];
}
