<?php
//
// File generated by Dolibarr installer 21.0.0-alpha on 25 jul. 2024
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='https://alixar:8080';
$dolibarr_main_document_root="/var/www/html/public/htdocs";
$dolibarr_main_data_root="/var/www/html/documents";
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='0';
$dolibarr_main_db_name='alixar_db';
$dolibarr_main_db_prefix='alx_';
$dolibarr_main_db_user='alixar_user';
$dolibarr_main_db_pass='alixar_password';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='1';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='25203cf0f97714064ec2bacafe948b5c';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH="";
//$dolibarr_lib_TCPDF_PATH="";
//$dolibarr_lib_FPDI_PATH="";
//$dolibarr_lib_TCPDI_PATH="";
//$dolibarr_lib_GEOIP_PATH="";
//$dolibarr_lib_NUSOAP_PATH="";
//$dolibarr_lib_ODTPHP_PATH="";
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP="";
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
